plugins {
    id 'application'
    id 'java'
    id 'jacoco'
}
repositories {
    mavenCentral()
}

test {
    testLogging.showStandardStreams = true
    finalizedBy jacocoTestReport
}
jacocoTestReport {
    dependsOn test
}

dependencies {
    testImplementation 'org.seleniumhq.selenium:selenium-java:3.141.59'
    testImplementation 'org.seleniumhq.selenium:selenium-firefox-driver:3.141.59'
    testImplementation('junit:junit:4.12'){
        exclude group: 'org.hamcrest'
    }
    testImplementation 'org.hamcrest:hamcrest-library:1.3'
    testImplementation "org.slf4j:slf4j-simple:1.7.9"

}